#!/usr/bin/env python3
"""Generate the first-strong bidi table from Unicode 16.0.0 DerivedBidiClass.

Usage: GenerateBidiClass.py path/to/DerivedBidiClass-16.0.0.txt
Input: https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedBidiClass.txt
"""
import hashlib
import pathlib
import re
import sys


def generate(source):
    raw = source.read_bytes()
    text = raw.decode("utf-8")
    if not text.startswith("# DerivedBidiClass-16.0.0.txt"):
        raise ValueError("Expected Unicode 16.0.0 DerivedBidiClass")
    directions = bytearray([1]) * 0x110000
    strong = {"L": 1, "R": 2, "AL": 2,
              "Left_To_Right": 1, "Right_To_Left": 2, "Arabic_Letter": 2}
    missing = []
    explicit = []
    for line in text.splitlines():
        match = re.match(r"# @missing: (.*)", line)
        data = match[1] if match else line.split("#", 1)[0].strip()
        if not data:
            continue
        region, kind = [part.strip() for part in data.split(";")]
        bounds = region.split("..")
        start = int(bounds[0], 16)
        end = int(bounds[-1], 16)
        (missing if match else explicit).append((start, end, strong.get(kind, 0)))
    for start, end, direction in missing + explicit:
        directions[start:end + 1] = bytes([direction]) * (end - start + 1)
    ranges = [0]
    for position in range(1, len(directions)):
        if directions[position] != directions[position - 1]:
            ranges.append(position)
    values = [(start << 2) | directions[start] for start in ranges]
    header = [
        "// Generated by scripts/GenerateBidiClass.py; do not edit the table.",
        "// Unicode 16.0.0 DerivedBidiClass: https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedBidiClass.txt",
        "// Data copyright (c) 2024 Unicode, Inc. License: ../LicenseUnicode.txt",
        f"// Input SHA256: {hashlib.sha256(raw).hexdigest()}",
        "// Two low bits: 0 = not strong, 1 = L, 2 = R or AL.",
        "inline constexpr unsigned int strongBidiRanges[] = {",
    ]
    header += ["\t" + ", ".join(f"0x{value:X}" for value in values[i:i + 8]) + ","
               for i in range(0, len(values), 8)]
    header += ["};", ""]
    destination = pathlib.Path(__file__).resolve().parent.parent / "src" / "BidiClassData.h"
    destination.write_text("\n".join(header), encoding="utf-8", newline="\n")
    print(f"Generated {len(values)} ranges in {destination}")


if __name__ == "__main__":
    generate(pathlib.Path(sys.argv[1]))
