#ifdef __GNUC__
#define _WIN32_IE 0x0600

	#ifndef LVS_OWNERDATA
		#define LVS_OWNERDATA 4096
	#endif

#endif

#define IDD_WINDOWS 7000
	#define IDC_WINDOWS_LIST (IDD_WINDOWS + 1)
	#define IDC_WINDOWS_SAVE (IDD_WINDOWS + 2)
	#define IDC_WINDOWS_CLOSE (IDD_WINDOWS + 3)
	#define IDC_WINDOWS_SORT (IDD_WINDOWS + 4)

#define IDR_WINDOWS_MENU 11000
	#define  IDM_WINDOW_WINDOWS   (IDR_WINDOWS_MENU + 1)
	#define  IDM_WINDOW_MRU_FIRST (IDR_WINDOWS_MENU + 20)
	#define  IDM_WINDOW_MRU_LIMIT (IDR_WINDOWS_MENU + 29)
