#!/bin/sh
# Reproduces PowerEditor/src/NppLibsVersion.h on Linux.
#
# The upstream build generates this header with a Windows-only .bat
# (NppLibsVersion-generator.bat) that shells out to cmd/findstr. On Linux
# there is no cmd, so we scrape the same three version strings from the
# vendored libraries and write the identical header here.
set -eu

ROOT="${1:?usage: gen-version-header.sh <repo-root>}"
OUT="$ROOT/PowerEditor/src/NppLibsVersion.h"

# extract <file> <define-prefix> -> the quoted value, e.g. 5.6.6
extract() {
	# grep the first matching line, keep only the "..." token
	grep -m1 -F "$2" "$1" 2>/dev/null | sed -E 's/.*"([^"]+)".*/\1/'
}

SCI=$(extract "$ROOT/scintilla/win32/ScintRes.rc"      '#define VERSION_SCINTILLA ' || true)
LEX=$(extract "$ROOT/lexilla/src/LexillaVersion.rc"    '#define VERSION_LEXILLA '   || true)
BST=$(extract "$ROOT/boostregex/boost/version.hpp"     '#define BOOST_LIB_VERSION ' || true)

: "${SCI:=N/A}"
: "${LEX:=N/A}"
: "${BST:=N/A}"

cat > "$OUT" <<EOF
// NppLibsVersion.h
// - generated by linux-deb/scripts/gen-version-header.sh (Linux equivalent of the upstream .bat)
#define NPP_SCINTILLA_VERSION "$SCI"
#define NPP_LEXILLA_VERSION "$LEX"
#define NPP_BOOST_REGEX_VERSION "$BST"
EOF

echo "gen-version-header: Scintilla=$SCI Lexilla=$LEX Boost=$BST -> $OUT"
