name: SAST – TruffleHog Secret Scan

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run TruffleHog to find secrets
        uses: trufflesecurity/trufflehog@main
        with:
          directory: .
