name: SAST – SonarCloud (Linux)

on:
  push:
    branches: [develop]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: meeesumpique661          # your SonarCloud org  
          projectKey: Meesum3595_notepad-plus-plus  # your project key  
          token: ${{ secrets.SONAR_TOKEN }}      # the secret you added  
